services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  server:
    build: ./server
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 5000:5000
    volumes:
      - ./server:/home/node/app
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
      DB_NAME: desafiosharenergy
      JWT_SECRET: JWT_SECRET@desafiosharenergy
      REFRESH_TOKEN_SECRET: REFRESH_TOKEN_SECRET@desafiosharenergy
      FRONTEND_URL: http://localhost:5173
      BASE_URL: http://localhost:5000

  client:
    build: ./client
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
    volumes:
      - ./client:/home/node/app
    depends_on:
      - server

volumes:
  mongodb_data: