### if you want to use this you will need the "Rest Client" extension in VSCode

### ----------------- USER -----------------
POST http://localhost:5000/users
Content-Type: application/json

{
  "username": "test",
  "password": "test123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "test",
  "password": "test123"
}

###
GET http://localhost:5000/users/profile
Authorization: Bearer token

###
GET http://localhost:5000/users
Authorization: Bearer token

###
GET http://localhost:5000/users/63bf78f74c74350913597181
Authorization: Bearer token

### ----------------- CLIENT -----------------
###
POST http://localhost:5000/clients
Authorization: Bearer token
Content-Type: application/json

{
  "name": "name",
  "email": "email",
  "phone": "phone",
  "address": "address",
  "cpf": "cpf"
}

###
POST http://localhost:5000/users/check-username-status
Content-Type: application/json

{
  "username": "desafiosharenergy"
}

###
GET http://localhost:5000/clients
Authorization: Bearer token

###
GET http://localhost:5000/clients/5a02a8c0-5b3b-4b82-9460-ff887c2e3dd3
Authorization: Bearer token

###
PATCH http://localhost:5000/clients/5a02a8c0-5b3b-4b82-9460-ff887c2e3dd3
Authorization: Bearer token
Content-Type: application/json

{
  "name":       "nameUpdated",
  "email":      "emailUpdated",
  "phone":      "phoneUpdated",
  "address":    "addressUpdated",
  "cpf":        "cpfUpdated"
}

###
DELETE http://localhost:5000/clients/5a02a8c0-5b3b-4b82-9460-ff887c2e3dd3
Authorization: Bearer token


### ----------------- AUTH -----------------
###
POST http://localhost:5000/refresh-token
Content-Type: application/json

{
  "refreshToken": "token"
}


### ----------------- IMAGE -----------------
###
GET http://localhost:5000/images/client-icons
Authorization: Bearer token